# Generated by Django 4.2.3 on 2023-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
