# Generated by Django 4.2.3 on 2023-07-06 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_interaction_created_at_alter_query_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 10, 46, 17, 877288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='query',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 10, 46, 17, 877013, tzinfo=datetime.timezone.utc)),
        ),
    ]
