# Generated by Django 4.2.3 on 2023-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_interaction_created_at_alter_query_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='chat_id',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
